import { expect, test } from '@playwright/test'

test('회원가입, 로그인 유지, 세션 복원과 로그아웃', async ({ page, browser }) => {
  const password = 'Browser-test-password-42'
  await page.goto('/documents/new')
  await expect(page).toHaveURL(/\/login\?redirect=/)
  await page.getByRole('link', { name: '회원가입', exact: true }).click()
  await page.getByLabel('이름', { exact: true }).fill('신규 회원')
  await page.getByLabel('이메일', { exact: true }).fill('browser-auth@example.com')
  await page.getByLabel('비밀번호', { exact: true }).fill(password)
  await page.getByLabel('비밀번호 확인', { exact: true }).fill('different-password')
  await page.getByRole('button', { name: '회원가입', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('비밀번호가 일치하지 않습니다.')
  await page.getByLabel('비밀번호 확인', { exact: true }).fill(password)
  await page.getByRole('button', { name: '회원가입', exact: true }).click()
  await expect(page).toHaveURL(/\/groups\/start$/)
  await page.getByRole('button', { name: /그룹 생성하기/ }).click()
  await page.getByLabel('그룹 이름').fill('인증 테스트 그룹')
  await page.getByRole('button', { name: '그룹 생성하기', exact: true }).click()
  await page.goto('/documents/new')
  await expect.poll(async () => (await page.context().cookies('http://127.0.0.1:5174/api/auth/me')).some(c => c.name === 'jerp_session')).toBe(true)
  const firstCookie = (await page.context().cookies('http://127.0.0.1:5174/api/auth/me')).find(c => c.name === 'jerp_session')!
  expect(firstCookie.httpOnly).toBe(true)
  expect(firstCookie.expires).toBe(-1)
  expect(await page.evaluate(() => sessionStorage.getItem('jerp-token'))).toBeNull()
  await page.reload()
  await expect(page.getByRole('button', { name: '로그아웃', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '로그아웃', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('이메일', { exact: true }).fill('browser-auth@example.com')
  await page.getByLabel('비밀번호', { exact: true }).fill('wrong-password')
  await page.getByRole('button', { name: '로그인', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('이메일 또는 비밀번호가 올바르지 않습니다.')
  await page.getByLabel('비밀번호', { exact: true }).fill(password)
  await page.getByLabel('로그인 상태 유지').check()
  await page.getByRole('button', { name: '로그인', exact: true }).click()
  await expect(page.getByRole('heading', { name: '신규 회원님, 안녕하세요.' })).toBeVisible()
  const state = await page.context().storageState()
  const persistent = state.cookies.find(c => c.name === 'jerp_session')!
  expect(persistent.expires).toBeGreaterThan(Date.now() / 1000 + 29 * 86400)
  const restored = await browser.newContext({ storageState: state })
  const otherPage = await restored.newPage()
  await otherPage.goto('http://127.0.0.1:5174/')
  await expect(otherPage.getByRole('heading', { name: '신규 회원님, 안녕하세요.' })).toBeVisible()
  await page.getByRole('button', { name: '로그아웃', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await otherPage.reload()
  await expect(otherPage).toHaveURL(/\/login/)
  await restored.close()
})
