import { expect, test } from '@playwright/test'

test('프로젝트 실행 관리와 ECR ECO 승인 흐름', async ({ page }) => {
  test.setTimeout(120000)
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  const password = 'Project-browser-test-42'
  const signup = await page.request.post('/api/auth/signup', { headers: { 'X-CSRF-Protection': '1' }, data: { name: '프로젝트 책임자', email: 'project-ui@example.com', password, password_confirm: password } })
  expect(signup.status()).toBe(201)
  const group = await (await page.request.post('/api/groups', { headers: { 'X-CSRF-Protection': '1' }, data: { name: '프로젝트 검증 그룹' } })).json()
  await page.goto('/projects')
  await page.evaluate(id => localStorage.setItem('jerp-group-id', String(id)), group.id)
  await page.reload()
  await page.getByRole('button', { name: '코인노래방 프로젝트 시작' }).click()
  await expect(page.getByRole('heading', { name: '코인노래방 1호점 오픈 프로젝트', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '지금 해야 할 일' })).toBeVisible()
  const tabs = page.getByRole('navigation', { name: '프로젝트 관리 메뉴' })
  expect(await tabs.getByRole('button').allTextContents()).toEqual(['개요', '업무', '계획', '통제', '자원'])
  const sub = page.getByRole('navigation', { name: '세부 관리 메뉴' })
  await tabs.getByRole('button', { name: '계획', exact: true }).click()
  await sub.getByRole('button', { name: 'WBS', exact: true }).click()
  await expect(page.locator('.wbs-tree button')).toHaveCount(14)
  await tabs.getByRole('button', { name: '업무', exact: true }).click()
  await page.getByRole('button', { name: '추가', exact: true }).click()
  await page.getByLabel('제목').fill('사업자 등록 준비')
  await page.getByLabel('업무 코드').fill('ACT-001')
  await page.getByLabel('우선순위').selectOption('P0')
  await page.getByLabel('목적', { exact: true }).fill('오픈 인허가 준비')
  await page.getByLabel('실행방법').fill('세무서에 필요 서류 확인')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.locator('.task-card').filter({ hasText: '사업자 등록 준비' })).toBeVisible()
  await page.locator('.task-card').filter({ hasText: '사업자 등록 준비' }).click()
  await expect(page.getByText('세무서에 필요 서류 확인', { exact: true })).toBeVisible()
  await page.getByLabel('댓글 내용').fill('서류 목록을 확인했습니다.')
  await page.getByRole('button', { name: '댓글 등록' }).click()
  await expect(page.getByText('서류 목록을 확인했습니다.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: '수정', exact: true }).click()
  await page.getByLabel('상태', { exact: true }).selectOption('IN_PROGRESS')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await tabs.getByRole('button', { name: '통제', exact: true }).click()
  await sub.getByRole('button', { name: '변경', exact: true }).click()
  await page.getByRole('button', { name: '추가', exact: true }).click()
  await page.getByLabel('변경 요청 제목').fill('오픈 일정 검토')
  await page.getByLabel('변경 사유').fill('인허가 일정 반영')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await page.locator('.change-list button').filter({ hasText: '오픈 일정 검토' }).click()
  for (const status of ['SUBMITTED', 'UNDER_REVIEW', 'APPROVED']) {
    await page.getByRole('button', { name: '수정', exact: true }).click()
    await page.getByLabel('상태', { exact: true }).selectOption(status)
    if (status === 'APPROVED') await page.getByLabel('승인·반려 근거').fill('영향 검토 완료')
    await page.getByRole('button', { name: '저장', exact: true }).click()
    await expect(page.getByRole('button', { name: '수정', exact: true })).toBeVisible()
  }
  await expect(page.locator('.change-stepper [aria-current=step]')).toHaveText('승인')
  await page.getByRole('button', { name: '변경 실행 시작', exact: true }).click()
  await page.getByLabel('실행 계획').fill('변경 일정을 공지하고 확인')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await page.getByRole('button', { name: '오픈 일정 검토', exact: true }).click()
  for (const status of ['IMPLEMENTING', 'VERIFYING', 'CLOSED']) {
    await page.getByRole('button', { name: '수정', exact: true }).click()
    await page.getByLabel('실행 상태', { exact: true }).selectOption(status)
    if (status === 'CLOSED') { await page.getByLabel('변경 후', { exact: true }).fill('변경 일정 반영'); await page.getByLabel('검증 결과').fill('공지 확인 완료') }
    await page.getByRole('button', { name: '저장', exact: true }).click()
    await expect(page.getByRole('button', { name: '수정', exact: true })).toBeVisible()
  }
  await expect(page.locator('.change-stepper [aria-current=step]')).toHaveText('종료')
  await tabs.getByRole('button', { name: '개요', exact: true }).click()
  await expect(page.locator('.next-actions')).toContainText('사업자 등록 준비')
  const projectId = new URL(page.url()).pathname.split('/').pop()
  const headers = { 'X-CSRF-Protection': '1', 'X-Group-ID': String(group.id) }
  for (const [kind, data] of Object.entries({
    risks: { title: '장비 납품 위험', probability: 5, impact: 4 },
    issues: { title: '현장 확인 필요', severity: 'HIGH' },
    decisions: { title: '운영 시간 확정', decision: '매일 운영', rationale: '수요 반영' },
    budget: { title: '장비 구입', planned_amount: 1000000, actual_amount: 200000 },
    vendors: { name: '장비 공급사' },
    milestones: { milestone_code: 'OPEN-1', name: '오픈 점검', planned_date: '2027-03-15' },
  })) expect((await page.request.post(`/api/projects/${projectId}/${kind}`, { headers, data })).status()).toBe(201)
  await page.reload()
  await expect(page.locator('.attention')).toContainText('장비 납품 위험')
  await expect(page.locator('.action-hero')).toHaveCount(1)
  await expect(page.locator('.workstream-grid button')).toHaveCount(14)
  await page.screenshot({ path: test.info().outputPath('workspace-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: '체크리스트', exact: true }).click()
  await expect(page.getByRole('heading', { name: '오픈 준비도', exact: true })).toBeVisible()
  await tabs.getByRole('button', { name: '계획', exact: true }).click()
  await expect(page.locator('.schedule-list')).toContainText('오픈 점검')
  await sub.getByRole('button', { name: '의존성', exact: true }).click()
  await expect(page.getByRole('heading', { name: '업무 의존성', exact: true })).toBeVisible()
  await tabs.getByRole('button', { name: '통제', exact: true }).click()
  await expect(page.getByRole('button', { name: '장비 납품 위험', exact: true })).toBeVisible()
  await sub.getByRole('button', { name: '이슈', exact: true }).click()
  await expect(page.getByRole('button', { name: '현장 확인 필요', exact: true })).toBeVisible()
  await sub.getByRole('button', { name: '의사결정', exact: true }).click()
  await expect(page.getByRole('button', { name: '운영 시간 확정', exact: true })).toBeVisible()
  await tabs.getByRole('button', { name: '자원', exact: true }).click()
  await expect(page.locator('.budget-summary')).toContainText('800,000원')
  await page.reload()
  await expect(page.locator('.workspace-nav [aria-current=page]')).toHaveText('자원')
  await sub.getByRole('button', { name: '업체', exact: true }).click()
  await expect(page.getByRole('button', { name: '장비 공급사', exact: true })).toBeVisible()
  await sub.getByRole('button', { name: '문서', exact: true }).click()
  await expect(page.getByRole('heading', { name: '관련 문서', exact: true })).toBeVisible()
  await tabs.getByRole('button', { name: '업무', exact: true }).click()
  const buckets = page.getByRole('navigation', { name: '업무 실행 단계' })
  await buckets.getByRole('button', { name: '지금', exact: true }).click()
  await expect(page.locator('.task-card')).toContainText('사업자 등록 준비')
  await buckets.getByRole('button', { name: '대기', exact: true }).click()
  await expect(page.locator('.task-card')).toHaveCount(0)
  await buckets.getByRole('button', { name: '전체', exact: true }).click()
  await expect(page.locator('.task-card')).toHaveCount(1)
  await page.setViewportSize({ width: 390, height: 844 })
  await tabs.getByRole('button', { name: '자원', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await tabs.getByRole('button', { name: '개요', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('workspace-mobile.png'), fullPage: true })
  expect(errors).toEqual([])
})
