import { expect, request as playwrightRequest, test, type Page } from '@playwright/test'

const workflowPassword = 'Workflow-test-password-42'
const workflowNames = ['홍길동', '김철수', '박영희', '최민수']
test.beforeAll(async () => {
  const contexts = []
  for (const [index, name] of workflowNames.entries()) {
    const context = await playwrightRequest.newContext({ baseURL: 'http://127.0.0.1:5174', extraHTTPHeaders: { 'X-CSRF-Protection': '1' } })
    contexts.push(context)
    const response = await context.post('/api/auth/signup', {
      headers: { 'X-CSRF-Protection': '1' },
      data: { name, email: `workflow${index}@example.com`, password: workflowPassword, password_confirm: workflowPassword },
    })
    expect(response.status()).toBe(201)
  }
  const created = await contexts[0].post('/api/groups', { data: { name: '브라우저 테스트 그룹' } })
  const group = await created.json()
  for (let index = 1; index < contexts.length; index++) {
    await contexts[index].post('/api/groups/join', { data: { code: group.code } })
  }
  const pending = await (await contexts[0].get(`/api/groups/${group.id}/pending`)).json()
  for (const membership of pending) {
    await contexts[0].post(`/api/groups/${group.id}/members/${membership.id}/approve`)
  }
  await Promise.all(contexts.map(context => context.dispose()))
})

async function login(page: Page, name: string) {
  await page.goto('/login')
  await page.getByLabel('이메일', { exact: true }).fill(`workflow${workflowNames.indexOf(name)}@example.com`)
  await page.getByLabel('비밀번호', { exact: true }).fill(workflowPassword)
  await page.getByRole('button', { name: '로그인', exact: true }).click()
  await expect(page.getByRole('heading', { name: `${name}님, 안녕하세요.` })).toBeVisible()
}
async function switchUser(page: Page, name: string) {
  await page.getByRole('button', { name: '로그아웃', exact: true }).click()
  await login(page, name)
}

test('작성 → 첨부 → 순차 결재 / 합의 → 완결 → 통보', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await login(page, '홍길동')
  await page.setViewportSize({ width: 1024, height: 768 })
  await expect(page.locator('.calendar-grid')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('dashboard-1024.png'), fullPage: true })
  await page.getByRole('main').getByRole('link', { name: '＋ 새 결재 작성', exact: true }).click()
  await page.getByLabel('제목', { exact: false }).fill('브라우저 검증 · 장비 구매')
  await page.getByLabel('내용', { exact: true }).fill('모니터 2대 구매를 요청합니다.\n김철수 결재 후 박영희 합의가 필요합니다.')
  await page.locator('input[type=file]').setInputFiles({ name: 'quotation.txt', mimeType: 'text/plain', buffer: Buffer.from('Quotation: 2 monitors') })
  await page.getByLabel('사용자 검색').fill('김')
  await page.getByRole('button', { name: /김철수.*추가/ }).click()
  await page.getByLabel('사용자 검색').fill('박')
  await page.getByRole('button', { name: /박영희.*추가/ }).click()
  await page.getByLabel('박영희 결재 유형').selectOption('AGREEMENT')
  await page.getByLabel('사용자 검색').fill('최')
  await page.getByRole('button', { name: /최민수.*추가/ }).click()
  await page.getByLabel('최민수 결재 유형').selectOption('NOTIFICATION')
  await page.getByRole('button', { name: '최민수 위로' }).click()
  await expect(page.locator('.approval-line li').nth(1)).toContainText('최민수')
  await page.getByRole('button', { name: '상신', exact: true }).click()
  await expect(page.locator('.badge')).toHaveText('상신중')
  const documentUrl = page.url()
  await expect(page.locator('.step-timeline li.CURRENT')).toContainText('김철수')
  await expect(page.getByRole('button', { name: '승인', exact: true })).toHaveCount(0)
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /quotation.txt/ }).click()
  expect((await downloadPromise).suggestedFilename()).toBe('quotation.txt')

  await switchUser(page, '박영희')
  await expect(page.locator('.pending-panel')).not.toContainText('브라우저 검증 · 장비 구매')
  await page.goto(documentUrl)
  await expect(page.getByRole('button', { name: '승인', exact: true })).toHaveCount(0)

  await switchUser(page, '김철수')
  await page.locator('.pending-panel').getByRole('link', { name: /브라우저 검증 · 장비 구매/ }).click()
  await page.getByLabel('결재 의견 / 반려 사유').fill('구매 필요성을 확인했습니다.')
  await page.getByRole('button', { name: '승인', exact: true }).click()
  await expect(page.locator('.step-timeline li.CURRENT')).toContainText('박영희')
  await expect(page.getByRole('button', { name: '승인', exact: true })).toHaveCount(0)
  await switchUser(page, '박영희')
  await page.locator('.pending-panel').getByRole('link', { name: /브라우저 검증 · 장비 구매/ }).click()
  await page.getByRole('button', { name: '승인', exact: true }).click()
  await expect(page.locator('.badge')).toHaveText('완결')
  await expect(page.locator('.step-timeline li.NOTIFIED')).toContainText('최민수')
  await page.screenshot({ path: testInfo.outputPath('completed-1024.png'), fullPage: true })
  await switchUser(page, '최민수')
  await page.getByRole('link', { name: /통보 문서/ }).click()
  await page.getByRole('link', { name: '브라우저 검증 · 장비 구매', exact: true }).click()
  await expect(page.locator('.badge')).toHaveText('완결')
  await switchUser(page, '홍길동')
  await page.goto(documentUrl)
  await expect(page.locator('.badge')).toHaveText('완결')
  expect(errors).toEqual([])
})

test('임시저장, 반려 사유 보존, 수정 후 재상신', async ({ page }) => {
  await login(page, '홍길동')
  await page.goto('/documents/new')
  await page.getByLabel('제목', { exact: false }).fill('수정 및 재상신 검증')
  await page.getByLabel('내용', { exact: true }).fill('초안')
  await page.getByRole('button', { name: /김철수.*추가/ }).click()
  await page.getByRole('button', { name: '임시저장', exact: true }).click()
  await expect(page).toHaveURL(/\/documents\/\d+\/edit$/)
  await expect(page.getByLabel('내용', { exact: true })).toHaveValue('초안')
  await page.getByRole('button', { name: '상신', exact: true }).click()
  await expect(page.locator('.badge')).toHaveText('상신중')
  const documentUrl = page.url()
  await switchUser(page, '김철수')
  await page.goto(documentUrl)
  await page.getByLabel('결재 의견 / 반려 사유').fill('견적 보완 필요')
  await page.getByRole('button', { name: '반려', exact: true }).click()
  await expect(page.locator('.badge')).toHaveText('기안')
  await switchUser(page, '홍길동')
  await page.goto(documentUrl)
  await page.getByRole('link', { name: '문서 수정', exact: true }).click()
  await page.getByLabel('내용', { exact: true }).fill('견적을 보완했습니다.')
  await page.getByRole('button', { name: '상신', exact: true }).click()
  await expect(page.locator('.history-list')).toContainText('견적 보완 필요')
  await expect(page.locator('.approval-detail > .muted')).toHaveText('2차 상신')
  await switchUser(page, '김철수')
  await page.goto(documentUrl)
  await page.getByRole('button', { name: '승인', exact: true }).click()
  await expect(page.locator('.badge')).toHaveText('완결')
})

test('개인 일정 추가·수정·삭제와 월 이동', async ({ page }) => {
  await login(page, '홍길동')
  await page.getByRole('link', { name: /그룹 일정/ }).click()
  await page.getByRole('button', { name: '＋ 일정', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('일정 제목').fill('브라우저 일정 검증')
  await dialog.getByLabel('하루 종일').check()
  await dialog.getByLabel('메모').fill('회의 자료 준비')
  await dialog.getByRole('button', { name: '일정 저장' }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: '브라우저 일정 검증', exact: true }).click()
  await dialog.getByLabel('일정 제목').fill('변경된 일정 검증')
  await dialog.getByRole('button', { name: '일정 저장' }).click()
  await expect(page.getByRole('button', { name: '변경된 일정 검증', exact: true })).toBeVisible()
  await switchUser(page, '김철수')
  await expect(page.locator('.calendar-grid')).toContainText('변경된 일정 검증')
  await switchUser(page, '홍길동')
  await page.getByRole('button', { name: '변경된 일정 검증', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await dialog.getByRole('button', { name: '일정 삭제' }).click()
  await expect(page.getByRole('button', { name: '변경된 일정 검증', exact: true })).toHaveCount(0)
  const previous = await page.locator('.calendar-toolbar h2').textContent()
  await page.getByRole('button', { name: '다음 달', exact: true }).click()
  await expect(page.locator('.calendar-toolbar h2')).not.toHaveText(previous!)
  await page.getByRole('button', { name: '오늘', exact: true }).click()
  await expect(page.locator('.calendar-toolbar h2')).toHaveText(previous!)
})
